Print the actual PDO error when reporting database connection problems.
When setting up Jethro, if one hasn't got the database settings correct, it is critical to see the error message.
Unfortunately Jethro's visible error message is generic:

```
Fatal error: Uncaught RuntimeException: Could not connect to database - please check for mistakes in your Database configuration in conf.php  , and check in MySQL that the database exists and the specified user has been granted access.
```

The real error message is reported via `error_log()`, which is nice, but a) the user doesn't know this, b) where
`error_log()` messages go is unclear.

This change puts the actual error up-front:

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1698] Access denied for user 'jethro'@'localhost' in /home/jethro/code/coastec/include/jethrodb.php:83 ...
```